In [1]:
%reload_ext autotimeimport pandas as pdpd.set_option('display.max_columns', None)#pd.set_option("display.max_colwidth", 200)import jsonfrom glob import globfrom tqdm.auto import tqdmimport osfrom bertopic import BERTopicfrom bertopic.representation import KeyBERTInspiredimport plotly.io as pioimport plotly.express as px # Plottingpio.renderers.default = 'notebook'pd.options.plotting.backend = "plotly"files = glob("supplements_results/*.json")len(files)

/mnt/timeout/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

346

time: 19.1 s (started: 2026-02-24 12:09:50 +13:00)

In [2]:
results = []for filename in tqdm(files):    with open(filename) as f:        try:            AI_data = json.load(f)        except:            print(f"Can't read {filename}")            continue            #os.remove(filename)    AI_data["AI_description"] = AI_data.pop("description")    metadata = filename.replace("results/", "videos/").replace(".result.json", ".info.json")    with open(metadata) as f:        meta = json.load(f)    keys = ['id', 'extractor', 'channel', 'channel_id', 'uploader', 'uploader_id', 'title', 'description', 'timestamp', 'view_count', 'like_count', 'comment_count', 'duration', 'upload_date', 'webpage_url']    result = {}    for key in keys:        result[key] = meta.get(key, None)    result.update(AI_data)    results.append(result)df = pd.DataFrame(results).sort_values("upload_date")df

 16%|█▌        | 55/346 [00:00<00:00, 539.17it/s]

Can't read supplements_results/5 Essential Vitamins Every Woman Should Take After 40 ｜ Women Health Tips ｜ Dr Rohit Gupta [S6-YJNo6dqo].result.json
Can't read supplements_results/Kalau kamu udah rutin konsumsi vitamin dan suplemen apa aja nih pas u... [7501538929640852744].result.json

 32%|███▏      | 109/346 [00:00<00:00, 480.38it/s]

Can't read supplements_results/How to pick a fiber supplement. If you’re interested, check out the f... [7607217455361969430].result.json

 62%|██████▏   | 216/346 [00:00<00:00, 516.03it/s]

Can't read supplements_results/#menopause full video on YouTube  [7575971082050604290].result.json
Can't read supplements_results/Estrogen and Dementia： What Every Woman Should Know for Perimenopause and Menopause [yya7qyxD_38].result.json
Can't read supplements_results/The Truth About Menopause  How Vitamin Supplements Really Work [JkO0wt93NJU].result.json
Can't read supplements_results/Full video on YouTube #menopause  [7574760814394019094].result.json

100%|██████████| 346/346 [00:00<00:00, 495.23it/s]

Can't read supplements_results/Este es uno de los mejores suplementos para mujeres ❤️ #suplementos #menopausia [pA7VmqXkj0U].result.json
Can't read supplements_results/วิตามินเเละอาหารเสริมตัวไหนเหมาะกับ ＂วัยทอง＂ [tKV8UK4F3wk].result.json
Can't read supplements_results/ಮುಟ್ಟು ನಿಂತ ನಂತರ ｜ After Menopause #kannada #kannadareels [TR8DVCAI28s].result.json
Can't read supplements_results/Most Supplements Weren’t Tested on Women ｜ Dr. Stacy Sims [-9jMK8ocWwg].result.json
Can't read supplements_results/Do you get jealous when your friends hangout without you？  #drewbarry... [7607894242786069791].result.json

,id,extractor,channel,channel_id,uploader,uploader_id,title,description,timestamp,view_count,like_count,comment_count,duration,upload_date,webpage_url,transcript,tone,supplements,active_ingredients,symptoms,menopause,language,marketing,job,sentiment,criticism,alternative_strategies,usefulness,misleading,quality,personal_experience,AI_description
261,w3ij_LuRvKw,youtube,Jon Stone,UCdDJ6sB2kssrqLB2d8mOsEA,Jon Stone,@jonstone69,What is FND?,Functional Neurological Disorder (FND) is a co...,1.573555e+09,265719.0,951.0,90.0,97.0,20191112,https://www.youtube.com/watch?v=w3ij_LuRvKw,What are Functional Neurological Disorders? Th...,Educational,No supplements mentioned,No active ingredients mentioned,"Functional gait disturbance, Functional tremor...",False,English,"Yes, it promotes the Australian FND Network.",doctor,Neutral,No criticism mentioned,Consulting a doctor,9,2,8,No personal experience mentioned,The video is an animated educational piece exp...
134,Mmk_N3cUNXY,youtube,Jon Stone,UCdDJ6sB2kssrqLB2d8mOsEA,Jon Stone,@jonstone69,How is FND treated?,FND treatments involve retraining the brain an...,1.573555e+09,98156.0,316.0,21.0,100.0,20191112,https://www.youtube.com/watch?v=Mmk_N3cUNXY,How are Functional Neurological Disorders trea...,Educational,No supplements mentioned,No active ingredients mentioned,Functional Neurological Disorders (FND),False,English,No marketing content,doctor,neutral,"The video criticizes pharmacological therapy, ...","psychological therapy, physiotherapy, occupati...",9,2,8,No personal experience mentioned,The video is an animated informational piece e...
44,0jv0K8-PjdA,youtube,Jon Stone,UCdDJ6sB2kssrqLB2d8mOsEA,Jon Stone,@jonstone69,What causes FND?,"Anyone can get FND. Physical injury, pain and ...",1.573555e+09,79805.0,213.0,14.0,60.0,20191112,https://www.youtube.com/watch?v=0jv0K8-PjdA,What causes Functional Neurological Disorders ...,Educational,No supplements mentioned,No active ingredients mentioned,"Functional Neurological Disorders, anxiety, de...",False,English,No marketing content,doctor,neutral,No criticism mentioned,No alternative strategies mentioned,9,2,8,No personal experience mentioned,The video is an educational animation explaini...
28,6880528670658678021,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,Top 4 Supplements For Menopause. Link In Bio ...,Top 4 Supplements For Menopause. Link In Bio ...,1.601998e+09,577100.0,22200.0,282.0,15.0,20201006,https://www.tiktok.com/@drmaryclaire/video/688...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium","Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",Menopause,True,English,The Pause Life (drmaryclaire),doctor,positive,No criticism mentioned,No alternative strategies mentioned,8,3,7,No personal experience mentioned,"A woman, identified as a doctor, stands in wha..."
50,6932157806711753989,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,#supplement in #menopause #foodismedicine#well...,#supplement in #menopause #foodismedicine#well...,1.614019e+09,240800.0,10400.0,260.0,13.0,20210222,https://www.tiktok.com/@drmaryclaire/video/693...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",No active ingredients mentioned,Menopause,True,English,No marketing content,"doctor, nurse",positive,No criticism mentioned,No alternative strategies mentioned,8,2,7,No personal experience mentioned,"A woman, appearing to be a medical professiona..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,7408529889801863697?region=my-1,html5,NaN,NaN,NaN,NaN,Pengambilan Vitamin Penting untuk Wanita Menop...,Ketahui vitamin yang penting untuk wanita meno...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mr.gen_pharmacist/...,Tiga vitamin yang sangat bagus untuk wanita me...,Educational,"Magnesium Bisglycinate, Sacha Inchi Oil with V...","Magnesium Bisglycinate, Sacha Inchi Oil, Vitam...","Stress, joint pain, body pain, muscle pain, in...",True,Malay,"Yes, the video shows and recommends specific s...",doctor,Positive,No criticism mentioned,Eating foods rich in the vitamins,8,3,7,No personal experience mentioned,The video is an informational segment presente...
147,7383515320331928069?region=us-1,html5,NaN,NaN,NaN,NaN,Top Foods for Menopause Relief and Effective F...,Discover the best foods to include for menopau...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@johnschaeferhealth...,Inflammation and menopause definitely plays a ...,Educational,No supplements mentioned,No active ingredients mentioned,"Inflammation, Fat loss",True,English,No marketing content,content creator,positive,No criticism,Include fatty fish and leafy greens,8,2,7,"The speaker mentions, 'Had this salad today, d...",A man in a teal shirt and baseball cap speaks ...
230,7447345169898406446?region=us-1,html5,NaN,NaN,NaN,NaN,Unlock Hormonal Balance: The Power of Triquetr...,Discover how Triquetra's Inositol supplement o...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@tandiekamcdonald/7...,"Listen, you're going to want to hide this thin...","Educational, promotional",Femositol Inositol Complex,"Myo-inositol, D-chiro-inositol","Hormone imbalance, Metabolic issues",True,English,Femositol Inositol Complex by Triquetra Therap...,content creator,positive,No criticism mentioned,No alternative strategies mentioned,7,3,6,The speaker mentions that her cousins will com...,The video displays a product called Femositol ...
298,7596998902545433096?region=sg-1,html5,NaN,NaN,NaN,NaN,One Powerful Supplement to Relieve Perimenopau...,Discover how Korra Lab Menopause Support combi...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mypreciouzkids/759...,Are you experiencing perimenopause symptoms li...,"Educational, promotional, and reassuring",Korra Lab Menopause Support,"Black Cohosh, Ashwagandha, Probiotics","Hot flashes, difficulty falling asleep, stiff ...",True,English,Korra Lab Menopause Support,"Influencer, content creator",Positive,No criticism mentioned,No alternative strategies mentioned,7,4,6,The speaker presents herself as someone who ha...,The video is a promotional advertisement for a...
306,7419706423078142481?region=my-1,html5,NaN,NaN,NaN,NaN,3 Vitamin Penting untuk Wanita Menopause (1),Ketahui 3 vitamin terbaik yang disarankan untu...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mr.gen_pharmacist/...,ada tiga vitamin yang best untuk wanita menopa...,Educational,"NMN, Astaxanthin, Coenzyme Q10","NMN, Astaxanthin, Coenzyme Q10","Fatigue, forgetfulness, skin dryness, wrinkles...",True,Malay,No marketing content,content creator,Positive,No criticism mentioned,No alternative strategies mentioned,7,3,6,No personal experience mentioned,A man in a blue shirt is sitting in the driver...

time: 738 ms (started: 2026-02-24 12:10:09 +13:00)

In [3]:
df.language.value_counts()

language
English              272
Spanish               13
Portuguese            11
Malay                 11
Hindi, English         5
Turkish                4
Indonesian             3
Filipino               2
Hindi and English      2
Telugu                 2
Hindi                  2
Punjabi                2
French                 1
Italian                1
Vietnamese             1
Russian                1
German                 1
Name: count, dtype: int64

time: 3.63 ms (started: 2026-02-24 12:10:10 +13:00)

In [4]:
sum(df.language!="English")

62

time: 1.95 ms (started: 2026-02-24 12:10:10 +13:00)

In [5]:
df.extractor.value_counts()

extractor
youtube      164
TikTok       115
facebook      42
html5          5
twitter        3
generic        3
Instagram      2
Name: count, dtype: int64

time: 3.22 ms (started: 2026-02-24 12:10:10 +13:00)

In [6]:
df.sentiment.value_counts()

sentiment
Positive    132
positive    120
Neutral      37
neutral      34
negative      6
Negative      5
Name: count, dtype: int64

time: 2.71 ms (started: 2026-02-24 12:10:10 +13:00)

In [7]:
df.to_excel("../data/supplements_LLM_results.xlsx", index=False)

time: 294 ms (started: 2026-02-24 12:10:10 +13:00)

In [8]:
df.menopause = df.menopause.astype(str)

time: 1.07 ms (started: 2026-02-24 12:10:10 +13:00)

In [9]:
df.menopause.value_counts()

menopause
True     274
False     60
Name: count, dtype: int64

time: 4.29 ms (started: 2026-02-24 12:10:10 +13:00)

In [10]:
df = df[df.menopause == "True"]df

,id,extractor,channel,channel_id,uploader,uploader_id,title,description,timestamp,view_count,like_count,comment_count,duration,upload_date,webpage_url,transcript,tone,supplements,active_ingredients,symptoms,menopause,language,marketing,job,sentiment,criticism,alternative_strategies,usefulness,misleading,quality,personal_experience,AI_description
28,6880528670658678021,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,Top 4 Supplements For Menopause. Link In Bio ...,Top 4 Supplements For Menopause. Link In Bio ...,1.601998e+09,577100.0,22200.0,282.0,15.0,20201006,https://www.tiktok.com/@drmaryclaire/video/688...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium","Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",Menopause,True,English,The Pause Life (drmaryclaire),doctor,positive,No criticism mentioned,No alternative strategies mentioned,8,3,7,No personal experience mentioned,"A woman, identified as a doctor, stands in wha..."
50,6932157806711753989,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,#supplement in #menopause #foodismedicine#well...,#supplement in #menopause #foodismedicine#well...,1.614019e+09,240800.0,10400.0,260.0,13.0,20210222,https://www.tiktok.com/@drmaryclaire/video/693...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",No active ingredients mentioned,Menopause,True,English,No marketing content,"doctor, nurse",positive,No criticism mentioned,No alternative strategies mentioned,8,2,7,No personal experience mentioned,"A woman, appearing to be a medical professiona..."
176,6938459316823346437,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,Vitamin D and Menopause #vitamind #menopause #...,Vitamin D and Menopause #vitamind #menopause #...,1.615486e+09,131400.0,8509.0,240.0,49.0,20210311,https://www.tiktok.com/@drmaryclaire/video/693...,No spoken content,Educational,Vitamin D,"Vitamin D2, Vitamin D3","Depression, Fatigue, Low immunity, Osteoporosis",True,English,No marketing content,"doctor, nurse",Positive,Toxicity is possible when taking large amounts...,"Sunlight exposure, Foods rich in Vitamin D",8,3,7,No personal experience mentioned,A woman wearing purple scrubs and a colorful s...
320,6942981025354009862,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,#healthy #womenover40 #womenover50 #menopause ...,#healthy #womenover40 #womenover50 #menopause ...,1.616539e+09,278000.0,22300.0,440.0,28.0,20210323,https://www.tiktok.com/@drmaryclaire/video/694...,Let's go girls. Come on. I'm going out tonight...,"Educational, enthusiastic, and informative.","Omega 3 Fatty Acids, Vitamin D, Calcium, Vitam...","Omega 3 Fatty Acids, Vitamin D, Calcium, Vitam...","Heart disease, high cholesterol, low triglycer...",True,English,The Galveston Diet,doctor,positive,No criticism mentioned,No alternative strategies mentioned,8,3,7,No personal experience mentioned,"A woman, identified as Dr. Mary Claire Haver, ..."
165,RxU4PtIR7Rs,youtube,"Heather Hirsch MD, MS, NCMP",UCrAeWep_qZiP7QeR7ogcCPA,"Heather Hirsch MD, MS, NCMP",@heatherhirschMD,Menopause weight gain explained in under 60 se...,Menopause weight gain explained in under 60 se...,1.626200e+09,16598.0,433.0,10.0,40.0,20210713,https://www.youtube.com/watch?v=RxU4PtIR7Rs,It's Dr. Hirsch here to talk about changes in ...,Educational,No supplements mentioned,No active ingredients mentioned,"Menopause, sleep trouble, binge eating, anxiet...",True,English,"Yes, the video promotes Dr. Heather Hirsch's w...",doctor,Neutral,No criticism mentioned,"Eat less, work out more",8,2,7,No personal experience mentioned,"A woman, identified as Dr. Heather Hirsch, spe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,7408529889801863697?region=my-1,html5,NaN,NaN,NaN,NaN,Pengambilan Vitamin Penting untuk Wanita Menop...,Ketahui vitamin yang penting untuk wanita meno...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mr.gen_pharmacist/...,Tiga vitamin yang sangat bagus untuk wanita me...,Educational,"Magnesium Bisglycinate, Sacha Inchi Oil with V...","Magnesium Bisglycinate, Sacha Inchi Oil, Vitam...","Stress, joint pain, body pain, muscle pain, in...",True,Malay,"Yes, the video shows and recommends specific s...",doctor,Positive,No criticism mentioned,Eating foods rich in the vitamins,8,3,7,No personal experience mentioned,The video is an informational segment presente...
147,7383515320331928069?region=us-1,html5,NaN,NaN,NaN,NaN,Top Foods for Menopause Relief and Effective F...,Discover the best foods to include for menopau...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@johnschaeferhealth...,Inflammation and menopause definitely plays a ...,Educational,No supplements mentioned,No active ingredients mentioned,"Inflammation, Fat loss",True,English,No marketing content,content creator,positive,No criticism,Include fatty fish and leafy greens,8,2,7,"The speaker mentions, 'Had this salad today, d...",A man in a teal shirt and baseball cap speaks ...
230,7447345169898406446?region=us-1,html5,NaN,NaN,NaN,NaN,Unlock Hormonal Balance: The Power of Triquetr...,Discover how Triquetra's Inositol supplement o...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@tandiekamcdonald/7...,"Listen, you're going to want to hide this thin...","Educational, promotional",Femositol Inositol Complex,"Myo-inositol, D-chiro-inositol","Hormone imbalance, Metabolic issues",True,English,Femositol Inositol Complex by Triquetra Therap...,content creator,positive,No criticism mentioned,No alternative strategies mentioned,7,3,6,The speaker mentions that her cousins will com...,The video displays a product called Femositol ...
298,7596998902545433096?region=sg-1,html5,NaN,NaN,NaN,NaN,One Powerful Supplement to Relieve Perimenopau...,Discover how Korra Lab Menopause Support combi...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mypreciouzkids/759...,Are you experiencing perimenopause symptoms li...,"Educational, promotional, and reassuring",Korra Lab Menopause Support,"Black Cohosh, Ashwagandha, Probiotics","Hot flashes, difficulty falling asleep, stiff ...",True,English,Korra Lab Menopause Support,"Influencer, content creator",Positive,No criticism mentioned,No alternative strategies mentioned,7,4,6,The speaker presents herself as someone who ha...,The video is a promotional advertisement for a...
306,7419706423078142481?region=my-1,html5,NaN,NaN,NaN,NaN,3 Vitamin Penting untuk Wanita Menopause (1),Ketahui 3 vitamin terbaik yang disarankan untu...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mr.gen_pharmacist/...,ada tiga vitamin yang best untuk wanita menopa...,Educational,"NMN, Astaxanthin, Coenzyme Q10","NMN, Astaxanthin, Coenzyme Q10","Fatigue, forgetfulness, skin dryness, wrinkles...",True,Malay,No marketing content,content creator,Positive,No criticism mentioned,No alternative strategies mentioned,7,3,6,No personal experience mentioned,A man in a blue shirt is sitting in the driver...

time: 26.3 ms (started: 2026-02-24 12:10:10 +13:00)

In [11]:
df["text"] = df.title.str.cat(df[["description", "transcript"]].astype(str), sep=" ")df

,id,extractor,channel,channel_id,uploader,uploader_id,title,description,timestamp,view_count,like_count,comment_count,duration,upload_date,webpage_url,transcript,tone,supplements,active_ingredients,symptoms,menopause,language,marketing,job,sentiment,criticism,alternative_strategies,usefulness,misleading,quality,personal_experience,AI_description,text
28,6880528670658678021,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,Top 4 Supplements For Menopause. Link In Bio ...,Top 4 Supplements For Menopause. Link In Bio ...,1.601998e+09,577100.0,22200.0,282.0,15.0,20201006,https://www.tiktok.com/@drmaryclaire/video/688...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium","Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",Menopause,True,English,The Pause Life (drmaryclaire),doctor,positive,No criticism mentioned,No alternative strategies mentioned,8,3,7,No personal experience mentioned,"A woman, identified as a doctor, stands in wha...",Top 4 Supplements For Menopause. Link In Bio ...
50,6932157806711753989,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,#supplement in #menopause #foodismedicine#well...,#supplement in #menopause #foodismedicine#well...,1.614019e+09,240800.0,10400.0,260.0,13.0,20210222,https://www.tiktok.com/@drmaryclaire/video/693...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",No active ingredients mentioned,Menopause,True,English,No marketing content,"doctor, nurse",positive,No criticism mentioned,No alternative strategies mentioned,8,2,7,No personal experience mentioned,"A woman, appearing to be a medical professiona...",#supplement in #menopause #foodismedicine#well...
176,6938459316823346437,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,Vitamin D and Menopause #vitamind #menopause #...,Vitamin D and Menopause #vitamind #menopause #...,1.615486e+09,131400.0,8509.0,240.0,49.0,20210311,https://www.tiktok.com/@drmaryclaire/video/693...,No spoken content,Educational,Vitamin D,"Vitamin D2, Vitamin D3","Depression, Fatigue, Low immunity, Osteoporosis",True,English,No marketing content,"doctor, nurse",Positive,Toxicity is possible when taking large amounts...,"Sunlight exposure, Foods rich in Vitamin D",8,3,7,No personal experience mentioned,A woman wearing purple scrubs and a colorful s...,Vitamin D and Menopause #vitamind #menopause #...
320,6942981025354009862,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,#healthy #womenover40 #womenover50 #menopause ...,#healthy #womenover40 #womenover50 #menopause ...,1.616539e+09,278000.0,22300.0,440.0,28.0,20210323,https://www.tiktok.com/@drmaryclaire/video/694...,Let's go girls. Come on. I'm going out tonight...,"Educational, enthusiastic, and informative.","Omega 3 Fatty Acids, Vitamin D, Calcium, Vitam...","Omega 3 Fatty Acids, Vitamin D, Calcium, Vitam...","Heart disease, high cholesterol, low triglycer...",True,English,The Galveston Diet,doctor,positive,No criticism mentioned,No alternative strategies mentioned,8,3,7,No personal experience mentioned,"A woman, identified as Dr. Mary Claire Haver, ...",#healthy #womenover40 #womenover50 #menopause ...
165,RxU4PtIR7Rs,youtube,"Heather Hirsch MD, MS, NCMP",UCrAeWep_qZiP7QeR7ogcCPA,"Heather Hirsch MD, MS, NCMP",@heatherhirschMD,Menopause weight gain explained in under 60 se...,Menopause weight gain explained in under 60 se...,1.626200e+09,16598.0,433.0,10.0,40.0,20210713,https://www.youtube.com/watch?v=RxU4PtIR7Rs,It's Dr. Hirsch here to talk about changes in ...,Educational,No supplements mentioned,No active ingredients mentioned,"Menopause, sleep trouble, binge eating, anxiet...",True,English,"Yes, the video promotes Dr. Heather Hirsch's w...",doctor,Neutral,No criticism mentioned,"Eat less, work out more",8,2,7,No personal experience mentioned,"A woman, identified as Dr. Heather Hirsch, spe...",Menopause weight gain explained in under 60 se...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,7408529889801863697?region=my-1,html5,NaN,NaN,NaN,NaN,Pengambilan Vitamin Penting untuk Wanita Menop...,Ketahui vitamin yang penting untuk wanita meno...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mr.gen_pharmacist/...,Tiga vitamin yang sangat bagus untuk wanita me...,Educational,"Magnesium Bisglycinate, Sacha Inchi Oil with V...","Magnesium Bisglycinate, Sacha Inchi Oil, Vitam...","Stress, joint pain, body pain, muscle pain, in...",True,Malay,"Yes, the video shows and recommends specific s...",doctor,Positive,No criticism mentioned,Eating foods rich in the vitamins,8,3,7,No personal experience mentioned,The video is an informational segment presente...,Pengambilan Vitamin Penting untuk Wanita Menop...
147,7383515320331928069?region=us-1,html5,NaN,NaN,NaN,NaN,Top Foods for Menopause Relief and Effective F...,Discover the best foods to include for menopau...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@johnschaeferhealth...,Inflammation and menopause definitely plays a ...,Educational,No supplements mentioned,No active ingredients mentioned,"Inflammation, Fat loss",True,English,No marketing content,content creator,positive,No criticism,Include fatty fish and leafy greens,8,2,7,"The speaker mentions, 'Had this salad today, d...",A man in a teal shirt and baseball cap speaks ...,Top Foods for Menopause Relief and Effective F...
230,7447345169898406446?region=us-1,html5,NaN,NaN,NaN,NaN,Unlock Hormonal Balance: The Power of Triquetr...,Discover how Triquetra's Inositol supplement o...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@tandiekamcdonald/7...,"Listen, you're going to want to hide this thin...","Educational, promotional",Femositol Inositol Complex,"Myo-inositol, D-chiro-inositol","Hormone imbalance, Metabolic issues",True,English,Femositol Inositol Complex by Triquetra Therap...,content creator,positive,No criticism mentioned,No alternative strategies mentioned,7,3,6,The speaker mentions that her cousins will com...,The video displays a product called Femositol ...,Unlock Hormonal Balance: The Power of Triquetr...
298,7596998902545433096?region=sg-1,html5,NaN,NaN,NaN,NaN,One Powerful Supplement to Relieve Perimenopau...,Discover how Korra Lab Menopause Support combi...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mypreciouzkids/759...,Are you experiencing perimenopause symptoms li...,"Educational, promotional, and reassuring",Korra Lab Menopause Support,"Black Cohosh, Ashwagandha, Probiotics","Hot flashes, difficulty falling asleep, stiff ...",True,English,Korra Lab Menopause Support,"Influencer, content creator",Positive,No criticism mentioned,No alternative strategies mentioned,7,4,6,The speaker presents herself as someone who ha...,The video is a promotional advertisement for a...,One Powerful Supplement to Relieve Perimenopau...
306,7419706423078142481?region=my-1,html5,NaN,NaN,NaN,NaN,3 Vitamin Penting untuk Wanita Menopause (1),Ketahui 3 vitamin terbaik yang disarankan untu...,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lemon8-app.com/@mr.gen_pharmacist/...,ada tiga vitamin yang best untuk wanita menopa...,Educational,"NMN, Astaxanthin, Coenzyme Q10","NMN, Astaxanthin, Coenzyme Q10","Fatigue, forgetfulness, skin dryness, wrinkles...",True,Malay,No marketing content,content creator,Positive,No criticism mentioned,No alternative strategies mentioned,7,3,6,No personal experience mentioned,A man in a blue shirt is sitting in the driver...,3 Vitamin Penting untuk Wanita Menopause (1) K...

time: 27.6 ms (started: 2026-02-24 12:10:11 +13:00)

In [12]:
df.index = pd.to_datetime(df.timestamp, unit='s')df = df.loc[df.index.dropna()]df

,id,extractor,channel,channel_id,uploader,uploader_id,title,description,timestamp,view_count,like_count,comment_count,duration,upload_date,webpage_url,transcript,tone,supplements,active_ingredients,symptoms,menopause,language,marketing,job,sentiment,criticism,alternative_strategies,usefulness,misleading,quality,personal_experience,AI_description,text
timestamp,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020-10-06 15:26:17,6880528670658678021,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,Top 4 Supplements For Menopause. Link In Bio ...,Top 4 Supplements For Menopause. Link In Bio ...,1.601998e+09,577100.0,22200.0,282.0,15.0,20201006,https://www.tiktok.com/@drmaryclaire/video/688...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium","Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",Menopause,True,English,The Pause Life (drmaryclaire),doctor,positive,No criticism mentioned,No alternative strategies mentioned,8,3,7,No personal experience mentioned,"A woman, identified as a doctor, stands in wha...",Top 4 Supplements For Menopause. Link In Bio ...
2021-02-22 18:32:56,6932157806711753989,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,#supplement in #menopause #foodismedicine#well...,#supplement in #menopause #foodismedicine#well...,1.614019e+09,240800.0,10400.0,260.0,13.0,20210222,https://www.tiktok.com/@drmaryclaire/video/693...,No spoken content,Educational,"Fiber, Omega-3 Fatty Acids, Vitamin D, Calcium",No active ingredients mentioned,Menopause,True,English,No marketing content,"doctor, nurse",positive,No criticism mentioned,No alternative strategies mentioned,8,2,7,No personal experience mentioned,"A woman, appearing to be a medical professiona...",#supplement in #menopause #foodismedicine#well...
2021-03-11 18:05:52,6938459316823346437,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,Vitamin D and Menopause #vitamind #menopause #...,Vitamin D and Menopause #vitamind #menopause #...,1.615486e+09,131400.0,8509.0,240.0,49.0,20210311,https://www.tiktok.com/@drmaryclaire/video/693...,No spoken content,Educational,Vitamin D,"Vitamin D2, Vitamin D3","Depression, Fatigue, Low immunity, Osteoporosis",True,English,No marketing content,"doctor, nurse",Positive,Toxicity is possible when taking large amounts...,"Sunlight exposure, Foods rich in Vitamin D",8,3,7,No personal experience mentioned,A woman wearing purple scrubs and a colorful s...,Vitamin D and Menopause #vitamind #menopause #...
2021-03-23 22:32:25,6942981025354009862,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,#healthy #womenover40 #womenover50 #menopause ...,#healthy #womenover40 #womenover50 #menopause ...,1.616539e+09,278000.0,22300.0,440.0,28.0,20210323,https://www.tiktok.com/@drmaryclaire/video/694...,Let's go girls. Come on. I'm going out tonight...,"Educational, enthusiastic, and informative.","Omega 3 Fatty Acids, Vitamin D, Calcium, Vitam...","Omega 3 Fatty Acids, Vitamin D, Calcium, Vitam...","Heart disease, high cholesterol, low triglycer...",True,English,The Galveston Diet,doctor,positive,No criticism mentioned,No alternative strategies mentioned,8,3,7,No personal experience mentioned,"A woman, identified as Dr. Mary Claire Haver, ...",#healthy #womenover40 #womenover50 #menopause ...
2021-07-13 18:13:48,RxU4PtIR7Rs,youtube,"Heather Hirsch MD, MS, NCMP",UCrAeWep_qZiP7QeR7ogcCPA,"Heather Hirsch MD, MS, NCMP",@heatherhirschMD,Menopause weight gain explained in under 60 se...,Menopause weight gain explained in under 60 se...,1.626200e+09,16598.0,433.0,10.0,40.0,20210713,https://www.youtube.com/watch?v=RxU4PtIR7Rs,It's Dr. Hirsch here to talk about changes in ...,Educational,No supplements mentioned,No active ingredients mentioned,"Menopause, sleep trouble, binge eating, anxiet...",True,English,"Yes, the video promotes Dr. Heather Hirsch's w...",doctor,Neutral,No criticism mentioned,"Eat less, work out more",8,2,7,No personal experience mentioned,"A woman, identified as Dr. Heather Hirsch, spe...",Menopause weight gain explained in under 60 se...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-17 10:44:35,7607783233866059030,TikTok,tiktokvic26,MS4wLjABAAAAJetnVlxj6PIJZRWD_or28VUeIWiEhVrbwM...,tiktokvic26,6915423128462476293,Menopause relief patches #menopause #menopausa...,Menopause relief patches #menopause #menopausa...,1.771325e+09,327.0,2.0,2.0,59.0,20260217,https://www.tiktok.com/@tiktokvic26/video/7607...,Calling all ladies out there of a certain age....,Informative and enthusiastic,Menopause Relief Patches,No active ingredients mentioned,Menopause,True,English,Stronglife Menopause Relief Patches,content creator,positive,No criticism mentioned,No alternative strategies mentioned,7,3,6,The speaker states that the patches have been ...,"A person is sitting on a couch, holding and di...",Menopause relief patches #menopause #menopausa...
2026-02-17 21:46:40,7607953795976269086,TikTok,Dr. Whitney Bowe,MS4wLjABAAAAFnGcPSn0y9NPpu1aW2Ik7uju2J2imL_7XS...,drwhitneybowe,6904311242254861317,"#stitch with @thatdorigirl Yes, yes, YES! I h...","#stitch with @thatdorigirl Yes, yes, YES! I h...",1.771365e+09,995.0,35.0,0.0,41.0,20260217,https://www.tiktok.com/@drwhitneybowe/video/76...,is it normal to wake up and look in the mirror...,Educational,"peptide serum, vitamin C, retinoid","peptides, vitamin C, retinoid","feeling like you've aged overnight, sagging sk...",True,English,"Yes, promoting Dr. Whitney Bowe's skincare adv...",doctor,positive,No criticism mentioned,"using a peptide serum, using a retinoid, being...",9,2,8,The speaker states that she hears this from he...,"The video features a woman, identified as Dr. ...","#stitch with @thatdorigirl Yes, yes, YES! I h..."
2026-02-17 22:08:54,7607959468751523085,TikTok,"Jay Jagannathan, MD",MS4wLjABAAAAZiKlYoVa_btD18dPQScAvqgckPN1SvSNeK...,jagannathanneurosurgery,7394892505346262062,"When we discuss menopause, the conversation us...","When we discuss menopause, the conversation us...",1.771366e+09,1168.0,23.0,7.0,6.0,20260217,https://www.tiktok.com/@jagannathanneurosurger...,"When we discuss menopause, the conversation us...","Educational, serious",No supplements mentioned,No active ingredients mentioned,"difficulty concentrating, losing words mid-sen...",True,English,No marketing content,doctor,neutral,No criticism mentioned,"proper evaluation, ruling out other conditions",9,2,7,No personal experience mentioned,"A man, identified as a doctor, is in what appe...","When we discuss menopause, the conversation us..."
2026-02-17 11:04:11,7607787672953736461,TikTok,The 'Pause Life,MS4wLjABAAAAPE4_0lfq7z4PBpxYKg0JSK7NYnf3oy8ZMQ...,drmaryclaire,6818706160898032645,"On this episode of unPAUSED, I’m joined by Aca...","On this episode of unPAUSED, I’m joined by Aca...",1.771326e+09,4215.0,217.0,5.0,86.0,20260217,https://www.tiktok.com/@drmaryclaire/video/760...,You know what? Here's the thing. I was still i...,"Educational, conversational, and empowering.",No supplements mentioned,No active ingredients mentioned,Menopause,True,English,"Yes, the podcast 'unPAUSED' and Naomi Watts's ...",doctor,Neutral,No criticism mentioned,No alternative strategies mentioned,8,2,9,"Yes, Naomi Watts shares her personal experienc...",The video is a promotional clip for a podcast ...,"On this episode of unPAUSED, I’m joined by Aca..."
2026-02-17 13:49:05,7607830779938295061,TikTok,Abbey Sharp,MS4wLjABAAAAAQv1HbaqXksgJi4dS26QQOjJAUW9MRpkeL...,abbeyskitchen,6907257538209039362,"I’m 38, which means perimenopause is right aro...","I’m 38, which means perimenopause is right aro...",1.771336e+09,2363.0,67.0,2.0,31.0,20260217,https://www.tiktok.com/@abbeyskitchen/video/76...,What did I do? Did I not do enough yoga? Did I...,"Educational, informative, and serious.",No supplements mentioned,No active ingredients mentioned,"Perimenopause, Menopause",True,English,"Yes, the video is marketing the 'Bite Back wit...",content creator,neutral,No criticism mentioned,No alternative strategies mentioned,9,2,8,No personal experience mentioned,The video is a promotional clip for a podcast ...,"I’m 38, which means perimenopause is right aro..."

time: 30.1 ms (started: 2026-02-24 12:10:11 +13:00)

In [30]:
topic_model = BERTopic(representation_model=KeyBERTInspired(), min_topic_size=3, verbose=True)topic_model.fit(df.text.str.replace(r"(menopausal|menopause|supplement|vitamin)", "", regex=True, case=False))topic_model.get_topic_info()

2026-02-24 12:16:13,379 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 9/9 [00:00<00:00, 26.82it/s]
2026-02-24 12:16:17,291 - BERTopic - Embedding - Completed ✓
2026-02-24 12:16:17,292 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-24 12:16:17,706 - BERTopic - Dimensionality - Completed ✓
2026-02-24 12:16:17,707 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-24 12:16:17,719 - BERTopic - Cluster - Completed ✓
2026-02-24 12:16:17,722 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-24 12:16:18,236 - BERTopic - Representation - Completed ✓

,Topic,Count,Name,Representation,Representative_Docs
0,-1,63,-1_health_hormone_hormones_body,"[health, hormone, hormones, body, estrogen, wo...",[Are s a Good Option For You? s and s: what i...
1,0,35,0_hormonal_hormone_magnesium_health,"[hormonal, hormone, magnesium, health, taking,...","[The Best s for Management At the age of 46, ..."
2,1,20,1_wellness_patients_women_obgyn,"[wellness, patients, women, obgyn, medical, gy...","[3 tips if you are in peri, or post Want to ..."
3,2,19,2_menopausa_menopausia_estradiol_metabolismo,"[menopausa, menopausia, estradiol, metabolismo...",[Por que mulheres respondem diferente à terapi...
4,3,17,3_estrogen_health_calcium_osteoporosis,"[estrogen, health, calcium, osteoporosis, defi...",[ D D deficiency is a major issue in —and it ...
5,4,14,4_mrgenpharmacist_b12_masalah_suplemen,"[mrgenpharmacist, b12, masalah, suplemen, agin...","[Replying to @kaklong82 Wanita atau pre , kal..."
6,5,13,5_doctor_health_dr_peri,"[doctor, health, dr, peri, hormone, integrativ...",[How to Advocate for Yourself In Peri and Her...
7,6,9,6_wellness_nutrition_health_healthy,"[wellness, nutrition, health, healthy, foodism...",[ D is crucial to our health. # #peri #galves....
8,7,9,7_hormone_ingredients_therapeutic_health,"[hormone, ingredients, therapeutic, health, ph...",[Be wary of “” branded s Be wary of “” brande...
9,8,9,8_nutrition_hormones_health_fitness,"[nutrition, hormones, health, fitness, exercis...",[Which s Should Women Take? | Dr. Stacy Sims o...
10,9,8,9_herbal_serum_gummies_thirties,"[herbal, serum, gummies, thirties, dr, relief,...",[Dr. Jen’s go-bag to help relieve symptoms Fr...
11,10,8,10_hormonebalance_phytoestrogens_hormones_hormone,"[hormonebalance, phytoestrogens, hormones, hor...",[ s: Must-Try s#nutrition Welcome to this vita...
12,11,7,11_health_healthy_biotin_nourishing,"[health, healthy, biotin, nourishing, treatmen...",[Hair Shedding in your 40's #peri #hairshedd...
13,12,7,12_health_yogurt_women_protein,"[health, yogurt, women, protein, serving, turm...",[ s The best s for health Dr. Mary Claire Hav...
14,13,6,13_dr_medical_womens_empowerment,"[dr, medical, womens, empowerment, women, naom...","[TANYA, 65 - there is life after How we talk ..."
15,14,6,14_nutrients_thrive_insulin_support,"[nutrients, thrive, insulin, support, estrogen...",[Shark Tank approved Multi Women 40+ 🌿 Shark T...
16,15,6,15_nutritionally_nutrition_bioactive_turmeric,"[nutritionally, nutrition, bioactive, turmeric...",[ s Even if you choose not to support our busi...
17,16,5,16_magnesium_b12_peri_pills,"[magnesium, b12, peri, pills, progesterone, pi...",[57K views · 298 reactions | Welcome to peri-!...
18,17,4,17_hormones_healthy_probiotics_health,"[hormones, healthy, probiotics, health, health...",[My 5 favorite s for women to live their best ...
19,18,4,18_nutrients_deficient_b12_placebo,"[nutrients, deficient, b12, placebo, symptom, ...",[Peri Brain Fog: Iron & D Solutions #shorts ...
20,19,4,19_hormones_estrogen_peri_exhausted,"[hormones, estrogen, peri, exhausted, women, s...","[Feeling off, exhausted, or dealing with night..."

time: 5.08 s (started: 2026-02-24 12:16:13 +13:00)

In [31]:
topic_model.visualize_topics()

time: 120 ms (started: 2026-02-24 12:16:22 +13:00)

In [32]:
topics_over_time = topic_model.topics_over_time(df.text, df.index, nr_bins=10)topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=20, height=600)

0it [00:00, ?it/s]

10it [00:02,  3.78it/s]

time: 2.76 s (started: 2026-02-24 12:16:25 +13:00)

In [33]:
df.resample('ME').size().plot(title="Number of videos uploaded over time")

time: 101 ms (started: 2026-02-24 12:16:34 +13:00)

In [34]:
df.sentiment = df.sentiment.str.lower()df.sentiment.value_counts()

sentiment
positive    218
neutral      46
negative      9
Name: count, dtype: int64

time: 9.54 ms (started: 2026-02-24 12:16:37 +13:00)

In [35]:
df.resample('ME').sentiment.value_counts().unstack().plot(title="Number of videos uploaded over time by sentiment", kind='bar')

time: 117 ms (started: 2026-02-24 12:16:38 +13:00)